name: dais_gold
version: "1.0.0"
config-version: 2

profile: dais

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dais_gold:
    +materialized: table
